version: '3.8'
services:
  mysql:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    container_name: authapp
    volumes:
      - ./mysql:/var/lib/mysql/
    ports:
      - 3306:3306
